'use server';

/**
 * @fileOverview Flow for generating an auto-generated portfolio for students.
 *
 * This file defines a Genkit flow that automatically generates a professional-looking portfolio
 * from a student's approved records. The portfolio can be used to showcase achievements
 * to potential employers or graduate schools.
 *
 * @interface AutoGeneratedPortfolioInput - Input type for the autoGeneratedPortfolio function.
 * @interface AutoGeneratedPortfolioOutput - Output type for the autoGeneratedPortfolio function.
 * @function autoGeneratedPortfolio - Main function to trigger the portfolio generation flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AutoGeneratedPortfolioInputSchema = z.object({
  studentName: z.string().describe('The name of the student.'),
  academicBackground: z.string().describe('The academic background of the student.'),
  skills: z.string().describe('The skills of the student.'),
  achievements: z.string().describe('The achievements of the student.'),
  activities: z.string().describe('The activities of the student.'),
});
export type AutoGeneratedPortfolioInput = z.infer<
  typeof AutoGeneratedPortfolioInputSchema
>;

const AutoGeneratedPortfolioOutputSchema = z.object({
  portfolioContent: z.string().describe('The generated portfolio content.'),
});
export type AutoGeneratedPortfolioOutput = z.infer<
  typeof AutoGeneratedPortfolioOutputSchema
>;

export async function autoGeneratedPortfolio(
  input: AutoGeneratedPortfolioInput
): Promise<AutoGeneratedPortfolioOutput> {
  return autoGeneratedPortfolioFlow(input);
}

const prompt = ai.definePrompt({
  name: 'autoGeneratedPortfolioPrompt',
  input: {schema: AutoGeneratedPortfolioInputSchema},
  output: {schema: AutoGeneratedPortfolioOutputSchema},
  prompt: `You are an AI assistant specialized in generating student portfolios.

  Create a professional-looking portfolio for the student with the following details:

  Student Name: {{{studentName}}}
  Academic Background: {{{academicBackground}}}
  Skills: {{{skills}}}
  Achievements: {{{achievements}}}
  Activities: {{{activities}}}

  Ensure the portfolio is well-structured, highlights the student's key accomplishments,
  and is suitable for showcasing to potential employers or graduate schools.
  Portfolio must be in a bio-data format. Portfolio must have a blue color scheme. The title of the portfolio should be "Student Portfolio".
  Make sure it is readable and attractive.
  `,
});

const autoGeneratedPortfolioFlow = ai.defineFlow(
  {
    name: 'autoGeneratedPortfolioFlow',
    inputSchema: AutoGeneratedPortfolioInputSchema,
    outputSchema: AutoGeneratedPortfolioOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
